{
    'name': 'Mercadolibre odoo',
    'version': '16.0.0.1',
    'description': 'Mercadolibre integration with odoo',
    'summary': 'Mercadolibre integration with odoo',
    'author': 'Vex Soluciones',
    'website': 'https://www.vexsoluciones.com',
    'license': 'OPL-1',
    'category': 'Uncategorized',
    'depends': [
        'base',
        'web',
        'stock', 
        'contacts',
        'sale_management',
        'delivery',
        'sale',
        'l10n_latam_base',
        'vex_syncronizer'
        ],
    'data': [
        'data/vex_cron.xml',
        'data/vex_cron_auto_republish.xml',
        'data/vex_cron_automatic_pricing.xml',
        'data/product_attribute_data.xml',
        'data/vex_data_category.xml',
        'data/vex_data_resapi_list.xml',
        'data/stock_location_data.xml',
        'data/vex_server_actions.xml',
        'views/vex_soluciones_restapi_list.xml',
        'views/vex_meli_action_list_view.xml',
        'views/vex_product_category.xml',
        #'views/vex_soluciones_category.xml',
        #'views/vex_soluciones_product_template.xml',
        'views/vex_soluciones_group_product_view.xml',
        'views/vex_soluciones_import_line.xml',       
        'views/vex_soluciones_product_pricelist.xml',
        'wizards/vex_soluciones_action.xml',
        #'views/vex_soluciones_sale_order_view.xml',
        'wizards/vex_soluciones_export_product.xml',
        'wizards/import_excel_wizard_views.xml',
        'wizards/vex_soluciones_mediation_menu.xml',
        #'security/vex_soluciones_instance_rules.xml',
        'security/ir_model_access.xml',
        'menus/menus.xml', 
        #'views/vex_soluciones_mediation_button_sale_order.xml',
        'views/vex_res_users_views_inherit.xml',    
        'views/vex_soluciones_export_product.xml',
        'views/vex_soluciones_ml.xml',
        'views/vex_pricing_rules_kanban_view.xml',
        #'views/vex_pricing_rules_tree_view.xml',
        #'views/vex_soluciones_republish_product.xml',
        'wizards/vex_soluciones_instance_selector.xml',
        'views/vex_soluciones_res_partner.xml',
        'views/vex_soluciones_market_competition.xml',
        'views/vex_soluciones_market_category.xml',
        'views/vex_soluciones_competition.xml',
        'views/vex_soluciones_my_reputation.xml',
        'wizards/vex_soluciones_add_rules_massive_wizard_view.xml',
        'views/vex_soluciones_dashboard_record.xml',
        'wizards/vex_soluciones_meli_sync_wizard_view.xml',
        'views/vex_webhook_queue.xml',
        'views/vex_instance.xml',
        'views/vex_product_template.xml',
        'data/marketplace_data.xml',
        'data/vex_partner.xml',
        'views/vex_sale_order.xml',
        'wizards/vex_soluciones_buttons_meli.xml',
    ],
    'demo': [],
    'auto_install': False,
    'application': False,
    #'price': 470.00,
    #'currency': 'USD',
    "assets": {
        "web.assets_backend": [
            "odoo-mercadolibre/static/src/js/gridstack-all.js",
            
            # MODULE VIEW
            "odoo-mercadolibre/static/src/module/vex_soluciones_dashboard.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_dashboard.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_questions.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_questions.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_forecast.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_forecast.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_mercado.xml",            
            "odoo-mercadolibre/static/src/module/vex_soluciones_mercado.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_pricing.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_pricing.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_product_ads.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_product_ads.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_brand_ads.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_brand_ads.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_display_ads.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_display_ads.js",

            "odoo-mercadolibre/static/src/module/vex_soluciones_notices.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_notices.js",
            
            #"odoo-mercadolibre/static/src/module/vex_soluciones_instance_selector.js",
            #"odoo-mercadolibre/static/src/module/vex_soluciones_instance_selector.xml",

            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings.xml",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings.js",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_stock.xml",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_stock.js",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_accountant.xml",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_accountant.js",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_general.xml",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_general.js",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_ai.xml",
            # "odoo-mercadolibre/static/src/module/vex_soluciones_settings_ai.js",
            
            "odoo-mercadolibre/static/src/module/vex_soluciones_chatbot.xml",
            "odoo-mercadolibre/static/src/module/vex_soluciones_chatbot.js",
            "odoo-mercadolibre/static/scss/global.scss",
            "odoo-mercadolibre/static/src/js/category_detail_view.js",
            "odoo-mercadolibre/static/src/js/form_visibility.js",
            "odoo-mercadolibre/static/src/xml/category_detail_template.xml",
            #"odoo-mercadolibre/static/src/js/license_view_interceptor.js",
            #"odoo-mercadolibre/static/src/js/components/InvalidLicenseDialog.js",
            #"odoo-mercadolibre/static/src/xml/invalid_license_dialog.xml",
        ],
         "web.assets_common": [

                "web/static/src/js/ajax.js",
                "odoo-mercadolibre/static/src/css/gridstack.css",
                "odoo-mercadolibre/static/src/css/gridstack-extra.css",
                "odoo-mercadolibre/static/src/css/global.css",
                "odoo-mercadolibre/static/src/css/global.scss",
                "odoo-mercadolibre/static/src/css/broadcast.css",
                "odoo-mercadolibre/static/src/css/navbar.css",
                "odoo-mercadolibre/static/src/css/button.css",
         ],
    }
}