#from . import vex_soluciones_instance
from . import vex_soluciones_logs
from . import vex_soluciones_meli_action_list
from . import vex_soluciones_meli_config
from . import vex_state_orders
from . import vex_soluciones_restapi_list
from . import vex_soluciones_category
from . import vex_soluciones_product
from . import vex_soluciones_res_partner
#from . import vex_soluciones_sale_order
from . import vex_soluciones_product_attributes
from . import vex_soluciones_group_product
from . import vex_soluciones_import_line
from . import vex_soluciones_synchro
from . import vex_soluciones_product_pricelist
from . import vex_soluciones_sku
from . import vex_soluciones_questions_meli
from . import vex_import_excel
from . import vex_soluciones_dashboard
from . import vex_soluciones_questions_automatic_response
from . import vex_webhook
from . import vex_gpt_config
from . import vex_prompt_history
from . import vex_soluciones_mediations
from . import vex_soluciones_mail_message_inherit
from . import vex_soluciones_menu_meditation
from . import vex_soluciones_mercadolibre_claims
from . import vex_soluciones_price_evolution
from . import vex_soluciones_automatic_pricing
from . import vex_res_users_views_inherit
from . import vex_soluciones_export_product
from . import vex_soluciones_api_ml
from . import vex_soluciones_meli_ads
from . import vex_soluciones_meli_notices
from . import vex_soluciones_meli_republish
from . import vex_soluciones_res_user
from . import vex_soluciones_competence_price_history
from . import vex_soluciones_market_competition
from . import vex_soluciones_market_category
from . import vex_soluciones_my_reputation
from . import vex_soluciones_trends
from . import vex_soluciones_competition
from . import vex_soluciones_product_performance_score
from . import vex_import_excel_mla
from . import vex_soluciones_category_trending_keyword
from . import vex_soluciones_import_order
from . import vex_soluciones_importador
#from . import vex_soluciones_stock
from . import vex_soluciones_dashboard_register
from . import vex_soluciones_meli_option
from . import vex_soluciones_meli_category
from . import vex_soluciones_meli_sync_job
from . import vex_soluciones_webhook_queues
from . import vex_instance
from . import vex_product_template
from . import vex_sync_queue
from . import vex_sale_order